development: &default
  secret_key_base: f59e96a6ac979a0a4bf113fbba16aceeb69d118e83562372d31ae5b60c00071f6521f277590b778e80ad40329f27726de953e81ac5ff3292261a6da79d631c60
  # secret_key_base: <%= ENV["SECRET_TOKEN"] %>

# production:
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default